### ISSUE TITLE
Focas Library For FreeBSD

### ISSUE THREAD

**Issue by PKhurjekar** [wheeliar/FANUC_Focas_API#1]
Due to pthreads issues ( thread local storage to be used ) on Linux , could you provide a Focas Library for FreeBSD. Also wanted to use FreeBSD. Thanks.

**Comment by wheeliar** [comment]
I think this library only support these linux distribution which described in official documents.
![image](https://github.com/wheeliar/FANUC_Focas_API/assets/30236449/d72a21df-e5c6-4ec2-9904-51c1655bc0ea)

you can try it.

**Comment by PKhurjekar** [comment]
I am.already using the library on Beaglebone with Debian  Linux.

Wanted to use Freebsd on Beaglebone with Focas.
